services:
  fnnas:
    container_name: fnnas
    image: qemux/qemu-docker
    environment:
      DISK_SIZE: "15G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      BOOT: "https://download.liveupdate.fnnas.com/x86_64/trim/TRIM-0.8.27-551.iso"
    volumes:
      - ./storage:/storage
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5666:5666
    stop_grace_period: 2m
